### ISSUE TITLE
[Android] `dotnet new android-fsharp` should create a copy of net6.0-android-fsharp

### ISSUE THREAD

**Issue by TimLariviere** [fabulousfx/net6.0-mobile-fsharp#1]
Following this documentation: https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-project-template

We need to package `net6.0-android-fsharp` as a template compatible with `dotnet new`.
Ideally, we will be able to do: `dotnet new android-fsharp -n MyAndroidApp`

**Comment by TimLariviere** [comment]
FYI @gsomix

**Comment by gsomix** [comment]
@TimLariviere OK, I'm on it.
