### ISSUE TITLE
Move to fsprojects?

### ISSUE THREAD

**Issue by knocte** [fabulousfx/net6.0-mobile-fsharp#22]
AFAIU these templates are not Fabolous-specific, so wouldn't it make more sense to move this repo out of the `fabolousfx` org?

**Comment by TimLariviere** [comment]
@knocte I understand the Fabulous org can confuse.
`fsprojects` is great but it's supposed to be an incubator, not a general purpose org for all F# repositories.

I could rename `fabulousfx` to `fsharp-mobile` since it's basically my goal: provide everything F# mobile tooling and frameworks.
Would that make sense?

**Comment by knocte** [comment]
> I could rename fabulousfx to fsharp-mobile

That sounds good, plus it would also solve the potential confusion from the fact that Fabolous actually lives in fsprojects instead of fabolousfx.

**Comment by knocte** [comment]
So I guess this can be closed now :) Thanks!

**Comment by knocte** [comment]
And now fsharp-mobile has been renamed to fabulous-dev? 😞

**Comment by TimLariviere** [comment]
Unfortunately yes. The change was requested by Don Syme when we asked to move Fabulous to this organization (https://github.com/fsprojects/.github/issues/45#issuecomment-1329229523)

You can now see Fabulous as a whole brand, beyond the MVU framework.
Our main product will be Fabulous itself, but we are also providing the mobile tools that we are using ourselves such as the  templates, Android.Resources helper, and such.

**Comment by knocte** [comment]
I understand what `fabulous-dev` is trying to do, but why not just move this single repo to fsprojects (and rename it to MauiTemplates, since Don didn't like the name "mobile" on it)?
