### ISSUE TITLE
.NET6.0 Maui templates?

### ISSUE THREAD

**Issue by knocte** [fabulousfx/net6.0-mobile-fsharp#24]
In case I'm not interested in the .NET7.0 Maui templates, what do I have to do to get the .NET6.0 ones?

**Comment by TimLariviere** [comment]
If you prefer to target .NET 6.0, you can either change the target framework directly in the fsproj file (eg. `net7.0` -> `net6.0`) or you can use the 1.0.x version of this repo:
https://www.nuget.org/packages/FSharp.Mobile.Templates/1.0.1

**Comment by knocte** [comment]
I've always had major problems when using nuget packages from github. How about creating a `stable` branch that maps with LTS versions (doesn't have the .NET7 upgrade commits).

**Comment by knocte** [comment]
e.g. a `stable-6.0` branch to points to this commit: https://github.com/fsharp-mobile/FSharp.Mobile.Templates/commit/d4dc921b7878c865f26795c64a735223b9d2e1d0 ?

> eg. net7.0 -> net6.0

I don't think it's that simple? FSharp.Core would need to be downgraded too AFAIU

**Comment by knocte** [comment]
(Edited comment above to add missing data.)

**Comment by TimLariviere** [comment]
@knocte I think FSharp.Core doesn't need to match the version of the .NET runtime you are using.
Mixing FSharp.Core 7.0 with .NET 6.0 should be fine.

https://fsharp.github.io/fsharp-compiler-docs/fsharp-core-notes.html#FSharp-Core-is-binary-compatible

>e.g. a stable-6.0 branch to points to this commit: https://github.com/fsharp-mobile/FSharp.Mobile.Templates/commit/d4dc921b7878c865f26795c64a735223b9d2e1d0 ?

I can do this easily, but I would like to better understand what benefits it would bring.
I don't mean it in a negative way. I'm genuinely interested as it can also benefit other of my repos.

Is it only about the fact .NET 6.0 is LTS and .NET 7.0 is not?
Is that a requirement at your company?

Given this repo is mainly created and maintained by me, I will mostly focus on the latest .NET version.
It is very unlikely I would push new packages targeting .NET 6.0.

**Comment by knocte** [comment]
> Is it only about the fact .NET 6.0 is LTS and .NET 7.0 is not?

Yes, and the fact that .NET6.0 is in ubuntu repos, while .NET7.0 isn't.

> Is that a requirement at your company?

Yes

> It is very unlikely I would push new packages targeting .NET 6.0.

Oh actually I'm not interested in the packages, just the templates. We will be using them soon to migrate from Mono+Xamarin.Forms to .NET6.0+XamarinForms, and some months later, from XF to Maui.

**Comment by TimLariviere** [comment]
I created the branch `stable-net6.0` on https://github.com/fsharp-mobile/FSharp.Mobile.Templates/commit/d4dc921b7878c865f26795c64a735223b9d2e1d0 like suggested.

**Comment by knocte** [comment]
Thank you.
